<?php

if ( function_exists( 'lazyblocks' ) ) :

lazyblocks()->add_block( array(
    'id' => 175,
    'title' => 'Block Style 2',
    'icon' => 'dashicons dashicons-admin-post',
    'keywords' => array(
    ),
    'slug' => 'lazyblock/block-2',
    'description' => '',
    'category' => 'lazyblocks',
    'category_label' => 'lazyblocks',
    'supports' => array(
        'customClassName' => true,
        'anchor' => false,
        'align' => array(
            0 => 'wide',
            1 => 'full',
        ),
        'html' => false,
        'multiple' => true,
        'inserter' => true,
    ),
    'ghostkit' => array(
        'supports' => array(
            'spacings' => false,
            'display' => false,
            'scrollReveal' => false,
        ),
    ),
    'controls' => array(
        'control_ef581b44b2' => array(
            'label' => 'Tile',
            'name' => 'tile',
            'type' => 'text',
            'child_of' => '',
            'default' => '',
            'characters_limit' => '',
            'placeholder' => '',
            'help' => '',
            'placement' => 'inspector',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'true',
            'save_in_meta_name' => '',
            'required' => 'false',
            'choices' => array(
            ),
            'checked' => 'false',
            'allow_null' => 'false',
            'multiple' => 'false',
            'allowed_mime_types' => array(
            ),
            'alpha' => 'false',
            'min' => '',
            'max' => '',
            'step' => '',
            'date_time_picker' => 'date_time',
            'multiline' => 'false',
            'rows_min' => '',
            'rows_max' => '',
            'rows_label' => '',
            'rows_add_button_label' => '',
            'rows_collapsible' => 'true',
            'rows_collapsed' => 'true',
        ),
        'control_f84abe4bb6' => array(
            'label' => 'Size',
            'name' => 'size',
            'type' => 'number',
            'child_of' => '',
            'default' => '',
            'characters_limit' => '',
            'placeholder' => '',
            'help' => '',
            'placement' => 'inspector',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'true',
            'save_in_meta_name' => '',
            'required' => 'false',
            'choices' => array(
            ),
            'checked' => 'false',
            'allow_null' => 'false',
            'multiple' => 'false',
            'allowed_mime_types' => array(
            ),
            'alpha' => 'false',
            'min' => '',
            'max' => '',
            'step' => '',
            'date_time_picker' => 'date_time',
            'multiline' => 'false',
            'rows_min' => '',
            'rows_max' => '',
            'rows_label' => '',
            'rows_add_button_label' => '',
            'rows_collapsible' => 'true',
            'rows_collapsed' => 'true',
        ),
        'control_6d99bd419a' => array(
            'label' => 'Select Categroy',
            'name' => 'select_categroy',
            'type' => 'select',
            'child_of' => '',
            'default' => '',
            'characters_limit' => '',
            'placeholder' => '',
            'help' => '',
            'placement' => 'inspector',
            'hide_if_not_selected' => 'false',
            'save_in_meta' => 'false',
            'save_in_meta_name' => '',
            'required' => 'false',
            'choices' => array(
                array(
                    'label' => 'Category 1',
                    'value' => 'Category 1',
                ),
                array(
                    'label' => 'Cat 2',
                    'value' => '2',
                ),
                array(
                    'label' => 'Cat 3',
                    'value' => '3',
                ),
                array(
                    'label' => 'Cat 4',
                    'value' => '4',
                ),
            ),
            'checked' => 'false',
            'allow_null' => 'false',
            'multiple' => 'false',
            'allowed_mime_types' => array(
            ),
            'alpha' => 'false',
            'min' => '',
            'max' => '',
            'step' => '',
            'date_time_picker' => 'date_time',
            'multiline' => 'false',
            'rows_min' => '',
            'rows_max' => '',
            'rows_label' => '',
            'rows_add_button_label' => '',
            'rows_collapsible' => 'true',
            'rows_collapsed' => 'true',
        ),
    ),
    'code' => array(
        'editor_html' => '<h1>Hello Block Style 01</h1>',
        'editor_callback' => '',
        'editor_css' => '',
        'frontend_html' => '<h1>Hello Block Style 01</h1>',
        'frontend_callback' => '',
        'frontend_css' => '',
        'show_preview' => 'always',
        'single_output' => false,
        'use_php' => false,
    ),
    'condition' => array(
        0 => 'page',
    ),
) );

endif;